services:
  rocket_download:
    build: .
    container_name: rocket_download

    volumes:
      - ./:/app
      - ./cache:/app/cache       

    environment:
      - PYTHONUNBUFFERED=1
      - SESSION_DIR=/app/cache    

    stdin_open: true
    tty: true
